"""Core layer: AI agent/model logic — tool definitions, path resolution, Ollama loading.

No UI dependencies (no Rich, no prompt_toolkit). See ui/ for the interactive layer.
"""

from .agent import MODEL, SYSTEM_PROMPT, load_llm, get_context_window
from .tools import (
    TOOLS,
    TOOLS_BY_NAME,
    PATH_ARGS,
    RG_BIN,
    resolve_paths,
    list_files,
    glob_files,
    rg_search,
    read_file,
    write_file,
    delete_file,
)
from .images import (
    ImageError,
    IMAGE_EXTS,
    is_image_path,
    resolve_image_path,
    parse_image_mentions,
    load_image_block,
    build_message_content,
)
from .messages import extract_text
from .sessions import (
    SESSIONS_DIR,
    STORED_SESSION_VERSION,
    StoredSession,
    StoredSessionMessage,
    ToolCallInfo,
    ToolResultInfo,
    RunEntry,
    RunStats,
    short_id,
    default_title,
    session_file_path,
    create_session,
    start_run,
    complete_run,
    fail_run,
    finish_run_from_messages,
    append_history_from_messages,
    save_session,
    flush_pending_writes,
)

__all__ = [
    "MODEL",
    "SYSTEM_PROMPT",
    "load_llm",
    "get_context_window",
    "TOOLS",
    "TOOLS_BY_NAME",
    "PATH_ARGS",
    "RG_BIN",
    "resolve_paths",
    "list_files",
    "glob_files",
    "rg_search",
    "read_file",
    "write_file",
    "delete_file",
    "ImageError",
    "IMAGE_EXTS",
    "is_image_path",
    "resolve_image_path",
    "parse_image_mentions",
    "load_image_block",
    "build_message_content",
    "extract_text",
    "SESSIONS_DIR",
    "STORED_SESSION_VERSION",
    "StoredSession",
    "StoredSessionMessage",
    "ToolCallInfo",
    "ToolResultInfo",
    "RunEntry",
    "RunStats",
    "short_id",
    "default_title",
    "session_file_path",
    "create_session",
    "start_run",
    "complete_run",
    "fail_run",
    "finish_run_from_messages",
    "append_history_from_messages",
    "save_session",
    "flush_pending_writes",
]
